# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'win1803'

steps:
- powershell: .\make.ps1 -Lint
  displayName: 'Lint Code'
- powershell: .\make.ps1 -Build
  displayName: 'Build'
- powershell: .\make.ps1 -Test
  displayName: 'Run Tests'